### ISSUE TITLE
Copy error? Kubernetes config map for Riak contains shell prompt line

### ISSUE THREAD

**Issue by samba** [netsil/manifests#65]
Since component files within the configmap `kubernetes/configmaps/auto-configmap.yml` appear to contain YAML, I assume they should all be valid YAML.

On line 111, you'll see:
```
root@gke-trafficsim-default-pool-93207d42-47ll:/etc/netsil-dd-agent/conf.d/auto_conf# vim riak
```

Since this file is [linked directly from the configuration instructions for Kubernetes][1], I hoped you'd find this tip helpful :)

[1]: https://docs.netsil.com/setup-guide/collectors/k8s/

**Comment by luhkevin** [comment]
Agh. Thanks for reporting this! Will fix right away.

**Comment by luhkevin** [comment]
Thanks. Closed with https://github.com/netsil/manifests/commit/cd6eb9b27c2ff1daa2b8e7f425bf3c98225fda17
